// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCduX_pPMR0yl0thASh9cEF-BtkFmsn-34',
    appId: '1:915143700556:web:0aee0e5ad0b0c7c57784e9',
    messagingSenderId: '915143700556',
    projectId: 'expensiya',
    authDomain: 'expensiya.firebaseapp.com',
    storageBucket: 'expensiya.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr4ZPljLnubdcqhMi0U86rT5R4vpng2GY',
    appId: '1:915143700556:android:963dee2dd69112be7784e9',
    messagingSenderId: '915143700556',
    projectId: 'expensiya',
    storageBucket: 'expensiya.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWQM7gmVMQalYqJ9zUHI-IG8YaNQo7OF8',
    appId: '1:915143700556:ios:3c1ec7b20944cea57784e9',
    messagingSenderId: '915143700556',
    projectId: 'expensiya',
    storageBucket: 'expensiya.appspot.com',
    iosClientId: '915143700556-k1l25t94hlb8icnurdo1doicmg5j8i5o.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWQM7gmVMQalYqJ9zUHI-IG8YaNQo7OF8',
    appId: '1:915143700556:ios:3c1ec7b20944cea57784e9',
    messagingSenderId: '915143700556',
    projectId: 'expensiya',
    storageBucket: 'expensiya.appspot.com',
    iosClientId: '915143700556-k1l25t94hlb8icnurdo1doicmg5j8i5o.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseManager',
  );
}
